// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: wallet_info.proto

package pb_wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletID                string  `protobuf:"bytes,1,opt,name=WalletID,proto3" json:"WalletID,omitempty"`
	LastDepositAmount       float64 `protobuf:"fixed64,2,opt,name=LastDepositAmount,proto3" json:"LastDepositAmount,omitempty"`
	RollingPeriodCumulative float64 `protobuf:"fixed64,3,opt,name=RollingPeriodCumulative,proto3" json:"RollingPeriodCumulative,omitempty"`
	AboveThreshold          bool    `protobuf:"varint,4,opt,name=AboveThreshold,proto3" json:"AboveThreshold,omitempty"`
	CreatedAt               int64   `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *WalletInfo) Reset() {
	*x = WalletInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wallet_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInfo) ProtoMessage() {}

func (x *WalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInfo.ProtoReflect.Descriptor instead.
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return file_wallet_info_proto_rawDescGZIP(), []int{0}
}

func (x *WalletInfo) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *WalletInfo) GetLastDepositAmount() float64 {
	if x != nil {
		return x.LastDepositAmount
	}
	return 0
}

func (x *WalletInfo) GetRollingPeriodCumulative() float64 {
	if x != nil {
		return x.RollingPeriodCumulative
	}
	return 0
}

func (x *WalletInfo) GetAboveThreshold() bool {
	if x != nil {
		return x.AboveThreshold
	}
	return false
}

func (x *WalletInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type WalletInfoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*WalletInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *WalletInfoList) Reset() {
	*x = WalletInfoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wallet_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInfoList) ProtoMessage() {}

func (x *WalletInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInfoList.ProtoReflect.Descriptor instead.
func (*WalletInfoList) Descriptor() ([]byte, []int) {
	return file_wallet_info_proto_rawDescGZIP(), []int{1}
}

func (x *WalletInfoList) GetList() []*WalletInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_wallet_info_proto protoreflect.FileDescriptor

var file_wallet_info_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xd6, 0x01, 0x0a, 0x0a, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11, 0x4c, 0x61, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x11, 0x4c, 0x61, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x38, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x17, 0x52, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x41, 0x62, 0x6f, 0x76, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x41, 0x62, 0x6f, 0x76, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x36, 0x0a, 0x0e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e,
	0x2f, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_wallet_info_proto_rawDescOnce sync.Once
	file_wallet_info_proto_rawDescData = file_wallet_info_proto_rawDesc
)

func file_wallet_info_proto_rawDescGZIP() []byte {
	file_wallet_info_proto_rawDescOnce.Do(func() {
		file_wallet_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_wallet_info_proto_rawDescData)
	})
	return file_wallet_info_proto_rawDescData
}

var file_wallet_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wallet_info_proto_goTypes = []interface{}{
	(*WalletInfo)(nil),     // 0: main.WalletInfo
	(*WalletInfoList)(nil), // 1: main.WalletInfoList
}
var file_wallet_info_proto_depIdxs = []int32{
	0, // 0: main.WalletInfoList.List:type_name -> main.WalletInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wallet_info_proto_init() }
func file_wallet_info_proto_init() {
	if File_wallet_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wallet_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wallet_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletInfoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wallet_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wallet_info_proto_goTypes,
		DependencyIndexes: file_wallet_info_proto_depIdxs,
		MessageInfos:      file_wallet_info_proto_msgTypes,
	}.Build()
	File_wallet_info_proto = out.File
	file_wallet_info_proto_rawDesc = nil
	file_wallet_info_proto_goTypes = nil
	file_wallet_info_proto_depIdxs = nil
}
